version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  telegram_bot:
    build: .
    command: python manage.py runbot
    volumes:
      - .:/app
    env_file:
      - .env

  predictor:
    build: .
    command: python manage.py predict --ticker TSLA
    volumes:
      - .:/app
    env_file:
      - .env
