# Generated by Django 5.2.4 on 2025-07-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_chat_id_userprofile_tg_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tg_user',
        ),
    ]
